language: php
sudo: false
dist: trusty

matrix:
  include:
    - php: 5.4
      env:
        - PHPUNIT_VERSION=^4.8
        - XDEBUG=1
    - php: 5.5
      env:
        - PHPUNIT_VERSION=^4.8
        - XDEBUG=1
    - php: 5.6
      env:
        - PHPUNIT_VERSION=^5.7
        - XDEBUG=1
    - php: 7.0
      env:
        - XDEBUG=1
        - PHPUNIT_VERSION=^5.7
    - php: 7.1
      env:
        - XDEBUG=1
        - PHPUNIT_VERSION=^7.5
    - php: 7.2
      env:
        - XDEBUG=1
        - PHPUNIT_VERSION=^7.5
    - php: 7.3
      env:
        - XDEBUG=1
        - PHPUNIT_VERSION=^8.0
  fast_finish: true
  allow_failures:
    - php: 7.3

before_script:
  - curl --version
  - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --dev --no-update -n
  - travis_retry composer install --no-interaction --prefer-source --dev
  - if [[ "$TRAVIS_PHP_VERSION" != "7.0" || "$TRAVIS_PHP_VERSION" != "7.1" ]]; then echo "xdebug.overload_var_dump = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini || true; fi
